### ISSUE TITLE
Make the default coercion more useful

### ISSUE THREAD

**Issue by rahulmutt** [metosin/compojure-api#192] opened 2016-01-04 12:15 UTC
I have an API call that takes a large number of parameters in the JSON body and the data comes in varied formats. For example, for a property 'qty' I want to make sure it's an integer and I'm OK with accepting "1" as a value as well - I just want it automatically converted into an integer, the correct format. I initially just set the schema as s/Int and expected it to "just work" but I ended up having to write my own custom coercer. The default behavior for s/Int is to do sc/safe-long-cast which calls (long) - and (long) only converted to a Long if the data is already numeric to begin with. 

Is there a reason why sc/safe-long-case is used in the json-coercions rather than string->long (much more useful) for the s/Int schema?

**Comment by Deraen** [comment] 2016-01-04 12:53
The JSON coercion is strict by design as it is good practice to use types provided by JSON.

I think it is good default to presume that clients correctly provide numbers as JSON numbers. However, we could probably make it easier to customize coercion.

**Comment by rahulmutt** [comment] 2016-01-04 13:01
Right. Basically there should be a way to say "I don't care what type of data comes in, I want it in this format, if possible." Maybe add a set of "forceful" coercers that completely change the data to be in the given format. I guess the best way to implement it is by adding an extra set of coercion matchers to compojure.api.coerce. If the idea sounds good, I'll submit a PR in the near future.

**Comment by Deraen** [comment] 2016-01-04 13:17
Could you provide an example of what you are currently doing, so we can see what are the problems with current API?

**Comment by ikitommi** [comment] 2016-01-04 13:39
Have you tried using the `query-schema-coercion-matcher` for the body? Is does the normal json stuff + converts numbers, booleans etc. from strings. You can override that at api level.

**Comment by rahulmutt** [comment] 2016-01-04 15:11
I looked at the query-schema-coercion-matcher, but I needed some functionality beyond that so I rolled out my own and added json-schema-coercion-matcher as a fallback for schemas that I didn't deal with.

This issue was mainly an inquiry whether it would be a good idea including a set of coercers to force the data into the desired format. 

Basically what's happening is that the API I'm working on is being called by code that we wrote for an older version of the platform. We're in position where we are not in control of the code update so we are forced to accommodate the older data formats. I'm using coercion to "clean" the data in a way.

I see no problems with the current API - I just feel stronger coercions should be available in the library for the convenience of the developer. For example, we take one property as product id. This product id is internally a string, but the user of the API can call it with a number as well since in the majority of the cases it's an integer, so I had to add a coercer for the s/Str schema to support this case. It's not a big deal to implement, but I felt it would be nice if the library had all these available through a top level setting like {:strong-coercions true}. 

The main benefit I see from adding these stronger coercers is a more flexible API more pleasant from the side of the person consuming the API. 

One thing that would make the API nicer is to have something like so:
```clojure
{:body-coercions {s/Str (fn [x] (str x))
                 s/Num (fn [x] (bigdec x))}
 :query-coercions {...}
 :path-coercions {...}
 :header-coercions {...}}
```
Each keyword takes a map of schema -> function that can transform the input data.

This should be available at the top level to configure the entire API or at the level of a route which can be done by overloading restructure-param.

**Comment by ikitommi** [comment] 2016-02-06 22:22
Hi, and thanks for your thoughts. Tested the current coercion and found it's bit too complex for common use cases (of just adding matchers). 

Did also a small modification to coercion internals in both c-api & ring-swagger, so this will work in the future in the client projects:

```clj
(def strong-coercions
  (constantly
    (constantly ring.swagger.coerce/query-schema-coercion-matcher)))

(s/defschema Types
  {:long Long
   :double Double
   :boolean Boolean})

(defapi app
  {:coercion strong-coercions
   :swagger {:ui "/", :spec "/swagger.json"}}
  (POST "/echo" []
    :return Types
    :body [body Types]
    (ok body)))
```

can consume any of
```json
{
  "long": 1,
  "double": 1.2,
  "boolean": true
}
```

```json
{
  "long": "1",
  "double": "1.2",
  "boolean": "true"
}
```

... the example always returning form presented in schema. Both changes in master, will be pushed to 1.0.0-RC2. Would this help in your case?

For the second part of "adding custom matchers". The proposed map of class=>converter has same signature as a schema matcher. I wouldn't add options for all ring-request parameter types as we have already flattened query, path and headers into type `:string`. So, the difference between the current `:coercion` and the proposal is that instead of needing to override all the matchers, one could say "add these". I think it's a good idea. Thinking aloud, either:

```clj
; effects all parameters
:matchers {s/Num string->number}

; just defined types
:matchers {:body {s/Num string->number}
          :string {s/Num string->number}}
```

**Comment by rahulmutt** [comment] 2016-02-07 08:20
Thanks, that's exactly what I was looking for. The :matchers syntax looks awesome. I will update my codebase once the 1.0.0 changes have settled down.

**Comment by ikitommi** [comment] 2016-07-15 11:57
Closing this as the original request was solved I thin, if you still want the matchers, please open a new issue.

**Closed by ikitommi** 2016-07-15 11:57 UTC
