### ISSUE TITLE
Failed to acquire keys which have default value.

### ISSUE THREAD

**Issue by defclass** [metosin/compojure-api#310] opened 2017-06-02 02:01 UTC
Hi,  I have simple route below

Example:
```clojure
(GET "/get_messages" []
     :query-params [{since :- s/Int nil}
                    {until :- s/Int nil}
                    {limit :- s/Int 20}
                    :as query-params]
     (prn query-params))
```
I have printed `query-params` Var at present , it seems didn't contains the keys which have default value.

Results:

`curl  /get_messages` => {}
`curl /get_messages?limit=10` => {:limit 10}

I expect :
`curl  /get_messages` => {:limit 20}

Or I missed some configurations, thanks for reading this post.

**Comment by ikitommi** [comment] 2017-06-02 06:22
Hi. This is originating from [Plumbing](https://github.com/plumatic/plumbing) `fnk`-syntax. Could you write issue there and link it to this issue? The corresponding plumbing code would be something like:

```clj
(require '[plumbing.core :refer :all])

(defnk get_messages
  [{since :- s/Int nil}
   {until :- s/Int nil}
   {limit :- s/Int 20}
   :as query-params]
  query-params)

(get_messages {})
; {}
```

**Comment by ikitommi** [comment] 2017-06-02 06:31
Also related: 

* https://github.com/metosin/compojure-api/issues/174
* https://github.com/metosin/schema-tools/issues/25

e.g. we could add a coercer to compojure-api, which would apply the defaults, but that still doesn't woudn't populate the `query-params` in your example with `fnk` syntax as Plumbing separates coercion from destructuring. It would work only when you define the Schema as data like with `:query`:

```clj
(GET "/defaults" []
  :query [query-params {:limit (st/default s/Int 10)}]
  (prn query-params))
```

**Comment by Deraen** [comment] 2017-06-02 09:23
IMO: Not a bug, works the same as Clojure default map destructuring:

```
(defn foo [{:keys [a b] :or {a 1 b 2} :as x}]
  x)

(foo {})
;; => {}
```

Default values from destructuring only work when referring the destructured value directly.

**Comment by defclass** [comment] 2017-06-02 09:44
Hi Tommi, thanks for your speedy reply and excellent solution. I've read the related links you provided.  It seems need Plumbing to provide this handy notation. 

According to @Deraen opinion,  maybe I went the wrong way, I'll try `st/default`, or provide default value in some other place where use the `query-params`. 

Cheers

**Comment by ikitommi** [comment] 2017-06-09 14:26
Closing this, continues on https://github.com/metosin/compojure-api/issues/174

**Closed by ikitommi** 2017-06-09 14:26 UTC
